### ISSUE TITLE
Response returned by GeoApify has problems

### ISSUE THREAD

**Issue by Aebel-Shajan** [Jean-005/Capstone_Project#38]
The response from GeoApify is:
```javascript
{
    "type": "FeatureCollection",
    "properties": {
        "mode": "drive",
        "params": {....},
        "issues": {
            "unassigned_shipments": [
                0,
                1,
                2,
                3,
                4
            ],
            "unassigned_agents": [
                0,
                1,
                2,
                3,
                4
            ]
        }
    },
    "features": []
}
```

The features array should not be empty and there should be not be any unassigned shipments or agents. We have a feeling this may be caused by the timeframe we provided or the number of orders we have.

**Comment by sahilpatel1906** [comment]
The geocodes within the dataloader were not the same format of (long, latitude) so needed to be changed to meet the requirements of the API.

**Comment by Aebel-Shajan** [comment]
One issue within the body was that the deliveryGeocode for each order was set to the same location. We looked in our backend and found out we made an error when creating new orders in the dataloader. 

![Screenshot 2024-04-15 at 19 34 52](https://github.com/Jean-005/Capstone_Project/assets/67755450/ddf82787-0276-4703-82d4-b455fe8678a4)

![Screenshot 2024-04-15 at 19 35 23](https://github.com/Jean-005/Capstone_Project/assets/67755450/af716a8a-792e-4c37-9a5f-e0c58b8b1f91)

**Comment by Aebel-Shajan** [comment]
This issue was caused by there not being a convention on the ordering of longitude and latitude.
![Lat_Long](https://github.com/Jean-005/Capstone_Project/assets/67755450/008340e3-fe4a-4a1c-b19e-5fea2a4d9cfe)

GeoApify uses (longitude, latitude)
![Geoapify](https://github.com/Jean-005/Capstone_Project/assets/67755450/83ef0e9e-8ee9-469f-ab85-31638be801cc)

Google maps uses (latitude, longitude)
![googleMaps](https://github.com/Jean-005/Capstone_Project/assets/67755450/a03a8fef-fdd2-447b-ad88-7124c59d9770)

**Comment by sahilpatel1906** [comment]
> This issue was caused by there not being a convention on the ordering of longitude and latitude. ![Lat_Long](https://private-user-images.githubusercontent.com/67755450/322597700-008340e3-fe4a-4a1c-b19e-5fea2a4d9cfe.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTMyMDgxODEsIm5iZiI6MTcxMzIwNzg4MSwicGF0aCI6Ii82Nzc1NTQ1MC8zMjI1OTc3MDAtMDA4MzQwZTMtZmU0YS00YTFjLWIxOWUtNWZlYTJhNGQ5Y2ZlLmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDE1VDE5MDQ0MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZhZjNkY2NlZWNmZTY0MDU2YWY0ZjNhOGUyNWVmYjM0MzJkM2MzMmEzOThhNGQxMGZiNTI3Njc2N2MwMGIwNDMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.GJIOgSUt55nvBEWtz7GNJWbh16PtaXABo6h04St0egU) [ ![Lat_Long](https://private-user-images.githubusercontent.com/67755450/322597700-008340e3-fe4a-4a1c-b19e-5fea2a4d9cfe.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTMyMDgxODEsIm5iZiI6MTcxMzIwNzg4MSwicGF0aCI6Ii82Nzc1NTQ1MC8zMjI1OTc3MDAtMDA4MzQwZTMtZmU0YS00YTFjLWIxOWUtNWZlYTJhNGQ5Y2ZlLmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDE1VDE5MDQ0MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZhZjNkY2NlZWNmZTY0MDU2YWY0ZjNhOGUyNWVmYjM0MzJkM2MzMmEzOThhNGQxMGZiNTI3Njc2N2MwMGIwNDMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.GJIOgSUt55nvBEWtz7GNJWbh16PtaXABo6h04St0egU) ](https://private-user-images.githubusercontent.com/67755450/322597700-008340e3-fe4a-4a1c-b19e-5fea2a4d9cfe.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTMyMDgxODEsIm5iZiI6MTcxMzIwNzg4MSwicGF0aCI6Ii82Nzc1NTQ1MC8zMjI1OTc3MDAtMDA4MzQwZTMtZmU0YS00YTFjLWIxOWUtNWZlYTJhNGQ5Y2ZlLmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDE1VDE5MDQ0MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZhZjNkY2NlZWNmZTY0MDU2YWY0ZjNhOGUyNWVmYjM0MzJkM2MzMmEzOThhNGQxMGZiNTI3Njc2N2MwMGIwNDMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.GJIOgSUt55nvBEWtz7GNJWbh16PtaXABo6h04St0egU) [ ](https://private-user-images.githubusercontent.com/67755450/322597700-008340e3-fe4a-4a1c-b19e-5fea2a4d9cfe.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTMyMDgxODEsIm5iZiI6MTcxMzIwNzg4MSwicGF0aCI6Ii82Nzc1NTQ1MC8zMjI1OTc3MDAtMDA4MzQwZTMtZmU0YS00YTFjLWIxOWUtNWZlYTJhNGQ5Y2ZlLmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDE1VDE5MDQ0MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZhZjNkY2NlZWNmZTY0MDU2YWY0ZjNhOGUyNWVmYjM0MzJkM2MzMmEzOThhNGQxMGZiNTI3Njc2N2MwMGIwNDMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.GJIOgSUt55nvBEWtz7GNJWbh16PtaXABo6h04St0egU)
> 
> GeoApify uses (longitude, latitude) ![Geoapify](https://private-user-images.githubusercontent.com/67755450/322598036-83ef0e9e-8ee9-469f-ab85-31638be801cc.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTMyMDgxODEsIm5iZiI6MTcxMzIwNzg4MSwicGF0aCI6Ii82Nzc1NTQ1MC8zMjI1OTgwMzYtODNlZjBlOWUtOGVlOS00NjlmLWFiODUtMzE2MzhiZTgwMWNjLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDE1VDE5MDQ0MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThiMGUzZTMzZmMzMGQ0NzdiMjEyMTQ4YWY2OTg2OThmYTZiMGZhNGYzNGFkNGNhMjY5NGFhN2M2OGRkNzFmZGImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.LC6QWX_9HSOieaN9lFQ2skpuQt0I07KvUbemXEMvAVE)
> 
> Google maps uses (latitude, longitude) ![googleMaps](https://private-user-images.githubusercontent.com/67755450/322598035-a03a8fef-fdd2-447b-ad88-7124c59d9770.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTMyMDgxODEsIm5iZiI6MTcxMzIwNzg4MSwicGF0aCI6Ii82Nzc1NTQ1MC8zMjI1OTgwMzUtYTAzYThmZWYtZmRkMi00NDdiLWFkODgtNzEyNGM1OWQ5NzcwLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDE1VDE5MDQ0MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM2OWYwM2ExOWJiMDM2MDY5ODRkNjA5NTY5ODZhNjA2NTYzYTI5ZjMwZDIxZmE5ODcxZGU0ZDE5YjJmZWEwYWMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.44FUNGojDmhm6heaR5yNS8ZPSsVoIdgKGn0sQ-g-zPA)

Can't believe we figured this out!
