### ISSUE TITLE
Unable to place markers on map

### ISSUE THREAD

**Issue by ney601** [Jean-005/Capstone_Project#58]
When trying to use the leaflet routing machine to display the routes, no route would be displayed even though we provided the waypoints for it.

**Comment by Aebel-Shajan** [comment]
I was able to fix this by adding a check in RouteDisplay.jsx which ensures that the MapContainer component does not get redered until a non empty route object is passed in.

```
  if(route.waypoints.length === 0) {
    return <p>Map loading</p>
  }
```
